quad:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    joint_motor_controller:
        type: velocity_controllers/JointGroupVelocityController
        #type: velocity_controllers/JointVelocityController
        joints: 
            - propjoint1
            - propjoint2
            - propjoint3
            - propjoint4
    #    pid: {p: 100.0, i: 0.01, d: 10.0}
    /gazebo_ros_control:
        pid_gains:
            propjoint1: {p: 100, i: 1, d: 10}
            propjoint2: {p: 100, i: 1, d: 10}
            propjoint3: {p: 100, i: 1, d: 10}
            propjoint4: {p: 100, i: 1, d: 10}
